---
abstract: 'Check extraneous/missing prerequisites in dist.ini'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-LintPrereqs
requires:
  Config::IniFiles: 0
  File::Which: 0
  Log::Any: 0
  Perinci::CmdLine: 0.62
  Perl::PrereqScanner: 0
  Sort::Versions: 0
  perl: 5.010001
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-LintPrereqs
  homepage: https://metacpan.org/release/App-LintPrereqs
  repository: git://github.com/sharyanto/perl-App-LintPrereqs.git
version: 0.13
